services:
  agent:
    build:
      context: .
      dockerfile: agent/Dockerfile
    env_file:
      - .env
    ports: ["52773:51773","51503:51403"]
    volumes:
      - ./agent/src:/opt/app
    entrypoint:
      - /bin/bash
      - /opt/app/start-all.sh    
    #  - ./iris.key:/tmp/iris.key
    #command:
    #  - --key
    #  - /tmp/iris.key
    environment:
      - TZ=JST-9

  wgagent:
    image: containers.intersystems.com/intersystems/webgateway:2026.1
    init: true
    ports:
      - 9992:80
      #- 443:443
    environment:
    - ISC_CSP_CONF_FILE=/webgateway-shared/CSP.conf
    - ISC_CSP_INI_FILE=/webgateway-shared/CSP.ini
    volumes:
    - ./webgateway-agent:/webgateway-shared
    # SSL有効化する場合は command 行のコメントを外します。
    #   SSL有効化する場合は、webgateway ディレクトリ内にSSL用の証明書と秘密鍵を配置してください。
    #   例）./webgateway/server.crt, ./webgateway/server.key
    #command: ["--ssl"]
