[mcp]
transport = "http"
host       = "0.0.0.0"     # bind address for HTTP/HTTPS transports
port       = 51403          # bind port
base_route = "/mcp"         # HTTP route prefix (default: /mcp)

[[iris]]
name   = "local"
server = { host = "localhost", port = 1972, username = "CSPSystem", password = "SYS" }
pool   = { min = 2, max = 5 }
tool_refresh_interval_secs = 30     # more frequent polling during development
endpoints = [
 { path = "/mcp/atest", username="SuperUser",password="SYS"},
  { path = "/mcp/btest", username="SuperUser",password="SYS"},
]

[logging]
level  = "debug"
output = "file"
file   = "/usr/irissys/mgr/iris-mcp.log"