###
# MCPのinitialize
POST http://localhost:51503/mcp
Accept: application/json, text/event-stream
Content-Type: application/json;charset=utf-8
Authorization: SuperUer:SYS

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "initialize",
  "params": {
    "protocolVersion": "2025-03-26",
    "capabilities": {},
    "clientInfo": {
      "name": "vscode-rest-client",
      "version": "0.1.0"
    }
  }
}

###
POST http://localhost:51503/mcp
Accept: application/json, text/event-stream
Content-Type: application/json;charset=utf-8
Mcp-Session-Id: 17e52481-b28f-4e12-ab83-1b77cb9f19da
Authorization: SuperUer:SYS

{
  "jsonrpc": "2.0",
  "id": 2,
  "method": "tools/list",
  "params": {}
}


### 池田さんテスト
POST http://localhost:51503/mcp
Accept: application/json, text/event-stream
Content-Type: application/json;charset=utf-8
Mcp-Session-Id: 17e52481-b28f-4e12-ab83-1b77cb9f19da
Authorization: SuperUer:SYS

{
  "jsonrpc": "2.0",
  "id": 3,
  "method": "tools/call",
  "params": {
    "name": "mcp_test_AskDatabase",
    "arguments": {
      "question": "男性の患者情報を教えて"
    }
  }
}

