###
# MCPのinitialize
POST http://localhost:51503/mcp
Accept: application/json, text/event-stream
Content-Type: application/json;charset=utf-8
Authorization: SuperUer:SYS

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "initialize",
  "params": {
    "protocolVersion": "2025-03-26",
    "capabilities": {},
    "clientInfo": {
      "name": "vscode-rest-client",
      "version": "0.1.0"
    }
  }
}

###
POST http://localhost:51503/mcp
Accept: application/json, text/event-stream
Content-Type: application/json;charset=utf-8
Mcp-Session-Id: 7ed38752-35be-4fef-98df-40e2a4166162
Authorization: SuperUer:SYS

{
  "jsonrpc": "2.0",
  "id": 2,
  "method": "tools/list",
  "params": {}
}


### mcp_btest_AskDatabase
POST http://localhost:51503/mcp
Accept: application/json, text/event-stream
Content-Type: application/json;charset=utf-8
Mcp-Session-Id: 7ed38752-35be-4fef-98df-40e2a4166162
Authorization: SuperUer:SYS

{
  "jsonrpc": "2.0",
  "id": 3,
  "method": "tools/call",
  "params": {
    "name": "mcp_btest_AskDatabase",
    "arguments": {
      "question": "What kind of data is available?"
    }
  }
}

