set $namespace="%SYS"
Do ##class(Security.Users).UnExpireUserPasswords("*")
Do ##class(Config.NLS.Locales).Install("jpuw")

// Embedded Python用にCallInサービスを有効化（現在の設定を取得）
set st=##class(Security.Services).Get("%Service_CallIn",.pro)
set pro("Enabled")=1
// 修正登録
set st=##class(Security.Services).Modify("%Service_CallIn",.pro)


//MCPサーバー用エンドポイント1
kill
set webName = "/mcp/atest"
set webProperties("DispatchClass") = "ATest.Service"
set webProperties("NameSpace") = "USER"
set webProperties("Enabled") = 1
set webProperties("AutheEnabled") = 96
set webProperties("MatchRoles")=":%All"
set webProperties("Type") = 18
Set webProperties("CookiePath")="/"
Set webProperties("Recurse")=1
Set webProperties("WSGICallable")=""
Set webProperties("WSGIDebug")=""
Set webProperties("WSGIType")=""
set st=##class(Security.Applications).Create(webName, .webProperties)
kill webProperties

//MCPサーバー用エンドポイント1
kill
set webName = "/mcp/btest"
set webProperties("DispatchClass") = "BTest.Service"
set webProperties("NameSpace") = "USER"
set webProperties("Enabled") = 1
set webProperties("AutheEnabled") = 96
set webProperties("MatchRoles")=":%All"
set webProperties("Type") = 18
Set webProperties("CookiePath")="/"
Set webProperties("Recurse")=1
Set webProperties("WSGICallable")=""
Set webProperties("WSGIDebug")=""
Set webProperties("WSGIType")=""
set st=##class(Security.Applications).Create(webName, .webProperties)
kill webProperties

// ネームスペース移動
set $namespace="USER"
// クラス定義インポート
do $System.OBJ.LoadDir("/opt/src/ATest","cku",,1)
do $System.OBJ.LoadDir("/opt/src/BTest","cku",,1)
